/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ContestType = { 'Damage' : null } |
  { 'TopPosition' : null } |
  { 'MostKills' : null };
export interface CreateTournamentArgs {
  'startTime' : Timestamp,
  'title' : string,
  'teamMode' : TeamMode,
  'contestType' : ContestType,
  'game' : Game,
  'viewMode' : ViewMode,
  'maxParticipants' : bigint,
  'entryFee' : bigint,
  'prizePool' : bigint,
}
export type Game = { 'BGMI' : null } |
  { 'FreeFire' : null };
export interface MatchResult {
  'damage' : bigint,
  'userId' : UserId,
  'earnings' : bigint,
  'position' : bigint,
  'tournamentId' : TournamentId,
  'kills' : bigint,
}
export type ParticipantStatus = { 'Eliminated' : null } |
  { 'Joined' : null } |
  { 'Completed' : null };
export interface ParticipantView {
  'status' : ParticipantStatus,
  'teamName' : [] | [string],
  'userId' : UserId,
  'tournamentId' : TournamentId,
}
export type TeamMode = { 'Duo' : null } |
  { 'Squad' : null } |
  { 'Solo' : null };
export type Timestamp = bigint;
export type TournamentId = bigint;
export type TournamentStatus = { 'Live' : null } |
  { 'WaitingResults' : null } |
  { 'RoomCodePosted' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null } |
  { 'Upcoming' : null };
export interface TournamentView {
  'id' : TournamentId,
  'startTime' : Timestamp,
  'status' : TournamentStatus,
  'title' : string,
  'teamMode' : TeamMode,
  'contestType' : ContestType,
  'currentParticipants' : bigint,
  'game' : Game,
  'roomPassword' : [] | [string],
  'viewMode' : ViewMode,
  'maxParticipants' : bigint,
  'entryFee' : bigint,
  'roomCode' : [] | [string],
  'prizePool' : bigint,
}
export interface Transaction {
  'id' : TransactionId,
  'userId' : UserId,
  'timestamp' : Timestamp,
  'txType' : TransactionType,
  'amount' : bigint,
  'tournamentId' : [] | [TournamentId],
  'reason' : TransactionReason,
}
export type TransactionId = bigint;
export type TransactionReason = { 'Refund' : null } |
  { 'EntryFee' : null } |
  { 'PrizeWin' : null } |
  { 'Signup' : null };
export type TransactionType = { 'Debit' : null } |
  { 'Credit' : null };
export type UserId = Principal;
export interface UserView {
  'id' : UserId,
  'username' : string,
  'createdAt' : Timestamp,
  'wins' : bigint,
  'totalEarnings' : bigint,
  'matchesPlayed' : bigint,
}
export type ViewMode = { 'FPP' : null } |
  { 'TPP' : null };
export interface _SERVICE {
  'adminAdjustBalance' : ActorMethod<
    [UserId, bigint, TransactionType],
    { 'ok' : null } |
      { 'userNotFound' : null } |
      { 'notAdmin' : null }
  >,
  'adminCreateTournament' : ActorMethod<
    [CreateTournamentArgs],
    { 'ok' : TournamentId } |
      { 'notAdmin' : null }
  >,
  'adminPostRoomCode' : ActorMethod<
    [TournamentId, string, [] | [string]],
    { 'ok' : null } |
      { 'notFound' : null } |
      { 'notAdmin' : null }
  >,
  'adminSubmitMatchResults' : ActorMethod<
    [TournamentId, Array<MatchResult>],
    { 'ok' : null } |
      { 'invalidStatus' : null } |
      { 'notFound' : null } |
      { 'notAdmin' : null }
  >,
  'adminUpdateTournamentStatus' : ActorMethod<
    [TournamentId, TournamentStatus],
    { 'ok' : null } |
      { 'notFound' : null } |
      { 'notAdmin' : null }
  >,
  'claimAdmin' : ActorMethod<
    [],
    { 'ok' : null } |
      { 'anonymous' : null } |
      { 'alreadyClaimed' : null }
  >,
  'getMatchResults' : ActorMethod<[TournamentId], Array<MatchResult>>,
  'getMyBalance' : ActorMethod<[], bigint>,
  'getMyProfile' : ActorMethod<[], [] | [UserView]>,
  'getMyTransactions' : ActorMethod<[], Array<Transaction>>,
  'getParticipants' : ActorMethod<[TournamentId], Array<ParticipantView>>,
  'getProfile' : ActorMethod<[UserId], [] | [UserView]>,
  'getTournament' : ActorMethod<[TournamentId], [] | [TournamentView]>,
  'isRegistered' : ActorMethod<[], boolean>,
  'joinTournament' : ActorMethod<
    [TournamentId, [] | [string]],
    { 'ok' : null } |
      { 'alreadyJoined' : null } |
      { 'tournamentFull' : null } |
      { 'insufficientFunds' : null } |
      { 'notJoinable' : null } |
      { 'notFound' : null } |
      { 'notRegistered' : null }
  >,
  'listTournaments' : ActorMethod<[], Array<TournamentView>>,
  'listUsers' : ActorMethod<[], Array<UserView>>,
  'register' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'anonymous' : null } |
      { 'alreadyRegistered' : null }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];