/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const TransactionType = IDL.Variant({
  'Debit' : IDL.Null,
  'Credit' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const TeamMode = IDL.Variant({
  'Duo' : IDL.Null,
  'Squad' : IDL.Null,
  'Solo' : IDL.Null,
});
export const ContestType = IDL.Variant({
  'Damage' : IDL.Null,
  'TopPosition' : IDL.Null,
  'MostKills' : IDL.Null,
});
export const Game = IDL.Variant({ 'BGMI' : IDL.Null, 'FreeFire' : IDL.Null });
export const ViewMode = IDL.Variant({ 'FPP' : IDL.Null, 'TPP' : IDL.Null });
export const CreateTournamentArgs = IDL.Record({
  'startTime' : Timestamp,
  'title' : IDL.Text,
  'teamMode' : TeamMode,
  'contestType' : ContestType,
  'game' : Game,
  'viewMode' : ViewMode,
  'maxParticipants' : IDL.Nat,
  'entryFee' : IDL.Nat,
  'prizePool' : IDL.Nat,
});
export const TournamentId = IDL.Nat;
export const MatchResult = IDL.Record({
  'damage' : IDL.Nat,
  'userId' : UserId,
  'earnings' : IDL.Nat,
  'position' : IDL.Nat,
  'tournamentId' : TournamentId,
  'kills' : IDL.Nat,
});
export const TournamentStatus = IDL.Variant({
  'Live' : IDL.Null,
  'WaitingResults' : IDL.Null,
  'RoomCodePosted' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
  'Upcoming' : IDL.Null,
});
export const UserView = IDL.Record({
  'id' : UserId,
  'username' : IDL.Text,
  'createdAt' : Timestamp,
  'wins' : IDL.Nat,
  'totalEarnings' : IDL.Nat,
  'matchesPlayed' : IDL.Nat,
});
export const TransactionId = IDL.Nat;
export const TransactionReason = IDL.Variant({
  'Refund' : IDL.Null,
  'EntryFee' : IDL.Null,
  'PrizeWin' : IDL.Null,
  'Signup' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : TransactionId,
  'userId' : UserId,
  'timestamp' : Timestamp,
  'txType' : TransactionType,
  'amount' : IDL.Nat,
  'tournamentId' : IDL.Opt(TournamentId),
  'reason' : TransactionReason,
});
export const ParticipantStatus = IDL.Variant({
  'Eliminated' : IDL.Null,
  'Joined' : IDL.Null,
  'Completed' : IDL.Null,
});
export const ParticipantView = IDL.Record({
  'status' : ParticipantStatus,
  'teamName' : IDL.Opt(IDL.Text),
  'userId' : UserId,
  'tournamentId' : TournamentId,
});
export const TournamentView = IDL.Record({
  'id' : TournamentId,
  'startTime' : Timestamp,
  'status' : TournamentStatus,
  'title' : IDL.Text,
  'teamMode' : TeamMode,
  'contestType' : ContestType,
  'currentParticipants' : IDL.Nat,
  'game' : Game,
  'roomPassword' : IDL.Opt(IDL.Text),
  'viewMode' : ViewMode,
  'maxParticipants' : IDL.Nat,
  'entryFee' : IDL.Nat,
  'roomCode' : IDL.Opt(IDL.Text),
  'prizePool' : IDL.Nat,
});

export const idlService = IDL.Service({
  'adminAdjustBalance' : IDL.Func(
      [UserId, IDL.Nat, TransactionType],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'userNotFound' : IDL.Null,
          'notAdmin' : IDL.Null,
        }),
      ],
      [],
    ),
  'adminCreateTournament' : IDL.Func(
      [CreateTournamentArgs],
      [IDL.Variant({ 'ok' : TournamentId, 'notAdmin' : IDL.Null })],
      [],
    ),
  'adminPostRoomCode' : IDL.Func(
      [TournamentId, IDL.Text, IDL.Opt(IDL.Text)],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'notFound' : IDL.Null,
          'notAdmin' : IDL.Null,
        }),
      ],
      [],
    ),
  'adminSubmitMatchResults' : IDL.Func(
      [TournamentId, IDL.Vec(MatchResult)],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'invalidStatus' : IDL.Null,
          'notFound' : IDL.Null,
          'notAdmin' : IDL.Null,
        }),
      ],
      [],
    ),
  'adminUpdateTournamentStatus' : IDL.Func(
      [TournamentId, TournamentStatus],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'notFound' : IDL.Null,
          'notAdmin' : IDL.Null,
        }),
      ],
      [],
    ),
  'claimAdmin' : IDL.Func(
      [],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'anonymous' : IDL.Null,
          'alreadyClaimed' : IDL.Null,
        }),
      ],
      [],
    ),
  'getMatchResults' : IDL.Func(
      [TournamentId],
      [IDL.Vec(MatchResult)],
      ['query'],
    ),
  'getMyBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserView)], ['query']),
  'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getParticipants' : IDL.Func(
      [TournamentId],
      [IDL.Vec(ParticipantView)],
      ['query'],
    ),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(UserView)], ['query']),
  'getTournament' : IDL.Func(
      [TournamentId],
      [IDL.Opt(TournamentView)],
      ['query'],
    ),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'joinTournament' : IDL.Func(
      [TournamentId, IDL.Opt(IDL.Text)],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'alreadyJoined' : IDL.Null,
          'tournamentFull' : IDL.Null,
          'insufficientFunds' : IDL.Null,
          'notJoinable' : IDL.Null,
          'notFound' : IDL.Null,
          'notRegistered' : IDL.Null,
        }),
      ],
      [],
    ),
  'listTournaments' : IDL.Func([], [IDL.Vec(TournamentView)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(UserView)], ['query']),
  'register' : IDL.Func(
      [IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'anonymous' : IDL.Null,
          'alreadyRegistered' : IDL.Null,
        }),
      ],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const TransactionType = IDL.Variant({
    'Debit' : IDL.Null,
    'Credit' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const TeamMode = IDL.Variant({
    'Duo' : IDL.Null,
    'Squad' : IDL.Null,
    'Solo' : IDL.Null,
  });
  const ContestType = IDL.Variant({
    'Damage' : IDL.Null,
    'TopPosition' : IDL.Null,
    'MostKills' : IDL.Null,
  });
  const Game = IDL.Variant({ 'BGMI' : IDL.Null, 'FreeFire' : IDL.Null });
  const ViewMode = IDL.Variant({ 'FPP' : IDL.Null, 'TPP' : IDL.Null });
  const CreateTournamentArgs = IDL.Record({
    'startTime' : Timestamp,
    'title' : IDL.Text,
    'teamMode' : TeamMode,
    'contestType' : ContestType,
    'game' : Game,
    'viewMode' : ViewMode,
    'maxParticipants' : IDL.Nat,
    'entryFee' : IDL.Nat,
    'prizePool' : IDL.Nat,
  });
  const TournamentId = IDL.Nat;
  const MatchResult = IDL.Record({
    'damage' : IDL.Nat,
    'userId' : UserId,
    'earnings' : IDL.Nat,
    'position' : IDL.Nat,
    'tournamentId' : TournamentId,
    'kills' : IDL.Nat,
  });
  const TournamentStatus = IDL.Variant({
    'Live' : IDL.Null,
    'WaitingResults' : IDL.Null,
    'RoomCodePosted' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
    'Upcoming' : IDL.Null,
  });
  const UserView = IDL.Record({
    'id' : UserId,
    'username' : IDL.Text,
    'createdAt' : Timestamp,
    'wins' : IDL.Nat,
    'totalEarnings' : IDL.Nat,
    'matchesPlayed' : IDL.Nat,
  });
  const TransactionId = IDL.Nat;
  const TransactionReason = IDL.Variant({
    'Refund' : IDL.Null,
    'EntryFee' : IDL.Null,
    'PrizeWin' : IDL.Null,
    'Signup' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : TransactionId,
    'userId' : UserId,
    'timestamp' : Timestamp,
    'txType' : TransactionType,
    'amount' : IDL.Nat,
    'tournamentId' : IDL.Opt(TournamentId),
    'reason' : TransactionReason,
  });
  const ParticipantStatus = IDL.Variant({
    'Eliminated' : IDL.Null,
    'Joined' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const ParticipantView = IDL.Record({
    'status' : ParticipantStatus,
    'teamName' : IDL.Opt(IDL.Text),
    'userId' : UserId,
    'tournamentId' : TournamentId,
  });
  const TournamentView = IDL.Record({
    'id' : TournamentId,
    'startTime' : Timestamp,
    'status' : TournamentStatus,
    'title' : IDL.Text,
    'teamMode' : TeamMode,
    'contestType' : ContestType,
    'currentParticipants' : IDL.Nat,
    'game' : Game,
    'roomPassword' : IDL.Opt(IDL.Text),
    'viewMode' : ViewMode,
    'maxParticipants' : IDL.Nat,
    'entryFee' : IDL.Nat,
    'roomCode' : IDL.Opt(IDL.Text),
    'prizePool' : IDL.Nat,
  });
  
  return IDL.Service({
    'adminAdjustBalance' : IDL.Func(
        [UserId, IDL.Nat, TransactionType],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'userNotFound' : IDL.Null,
            'notAdmin' : IDL.Null,
          }),
        ],
        [],
      ),
    'adminCreateTournament' : IDL.Func(
        [CreateTournamentArgs],
        [IDL.Variant({ 'ok' : TournamentId, 'notAdmin' : IDL.Null })],
        [],
      ),
    'adminPostRoomCode' : IDL.Func(
        [TournamentId, IDL.Text, IDL.Opt(IDL.Text)],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'notFound' : IDL.Null,
            'notAdmin' : IDL.Null,
          }),
        ],
        [],
      ),
    'adminSubmitMatchResults' : IDL.Func(
        [TournamentId, IDL.Vec(MatchResult)],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'invalidStatus' : IDL.Null,
            'notFound' : IDL.Null,
            'notAdmin' : IDL.Null,
          }),
        ],
        [],
      ),
    'adminUpdateTournamentStatus' : IDL.Func(
        [TournamentId, TournamentStatus],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'notFound' : IDL.Null,
            'notAdmin' : IDL.Null,
          }),
        ],
        [],
      ),
    'claimAdmin' : IDL.Func(
        [],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'anonymous' : IDL.Null,
            'alreadyClaimed' : IDL.Null,
          }),
        ],
        [],
      ),
    'getMatchResults' : IDL.Func(
        [TournamentId],
        [IDL.Vec(MatchResult)],
        ['query'],
      ),
    'getMyBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserView)], ['query']),
    'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getParticipants' : IDL.Func(
        [TournamentId],
        [IDL.Vec(ParticipantView)],
        ['query'],
      ),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(UserView)], ['query']),
    'getTournament' : IDL.Func(
        [TournamentId],
        [IDL.Opt(TournamentView)],
        ['query'],
      ),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'joinTournament' : IDL.Func(
        [TournamentId, IDL.Opt(IDL.Text)],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'alreadyJoined' : IDL.Null,
            'tournamentFull' : IDL.Null,
            'insufficientFunds' : IDL.Null,
            'notJoinable' : IDL.Null,
            'notFound' : IDL.Null,
            'notRegistered' : IDL.Null,
          }),
        ],
        [],
      ),
    'listTournaments' : IDL.Func([], [IDL.Vec(TournamentView)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(UserView)], ['query']),
    'register' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'anonymous' : IDL.Null,
            'alreadyRegistered' : IDL.Null,
          }),
        ],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };