/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TournamentView {
    id: TournamentId;
    startTime: Timestamp;
    status: TournamentStatus;
    title: string;
    teamMode: TeamMode;
    contestType: ContestType;
    currentParticipants: bigint;
    game: Game;
    roomPassword?: string;
    viewMode: ViewMode;
    maxParticipants: bigint;
    entryFee: bigint;
    roomCode?: string;
    prizePool: bigint;
}
export interface UserView {
    id: UserId;
    username: string;
    createdAt: Timestamp;
    wins: bigint;
    totalEarnings: bigint;
    matchesPlayed: bigint;
}
export interface ParticipantView {
    status: ParticipantStatus;
    teamName?: string;
    userId: UserId;
    tournamentId: TournamentId;
}
export type TournamentId = bigint;
export type UserId = Principal;
export type TransactionId = bigint;
export interface Transaction {
    id: TransactionId;
    userId: UserId;
    timestamp: Timestamp;
    txType: TransactionType;
    amount: bigint;
    tournamentId?: TournamentId;
    reason: TransactionReason;
}
export interface MatchResult {
    damage: bigint;
    userId: UserId;
    earnings: bigint;
    position: bigint;
    tournamentId: TournamentId;
    kills: bigint;
}
export interface CreateTournamentArgs {
    startTime: Timestamp;
    title: string;
    teamMode: TeamMode;
    contestType: ContestType;
    game: Game;
    viewMode: ViewMode;
    maxParticipants: bigint;
    entryFee: bigint;
    prizePool: bigint;
}
export enum ContestType {
    Damage = "Damage",
    TopPosition = "TopPosition",
    MostKills = "MostKills"
}
export enum Game {
    BGMI = "BGMI",
    FreeFire = "FreeFire"
}
export enum ParticipantStatus {
    Eliminated = "Eliminated",
    Joined = "Joined",
    Completed = "Completed"
}
export enum TeamMode {
    Duo = "Duo",
    Squad = "Squad",
    Solo = "Solo"
}
export enum TournamentStatus {
    Live = "Live",
    WaitingResults = "WaitingResults",
    RoomCodePosted = "RoomCodePosted",
    Cancelled = "Cancelled",
    Completed = "Completed",
    Upcoming = "Upcoming"
}
export enum TransactionReason {
    Refund = "Refund",
    EntryFee = "EntryFee",
    PrizeWin = "PrizeWin",
    Signup = "Signup"
}
export enum TransactionType {
    Debit = "Debit",
    Credit = "Credit"
}
export enum Variant_ok_alreadyJoined_tournamentFull_insufficientFunds_notJoinable_notFound_notRegistered {
    ok = "ok",
    alreadyJoined = "alreadyJoined",
    tournamentFull = "tournamentFull",
    insufficientFunds = "insufficientFunds",
    notJoinable = "notJoinable",
    notFound = "notFound",
    notRegistered = "notRegistered"
}
export enum Variant_ok_anonymous_alreadyClaimed {
    ok = "ok",
    anonymous = "anonymous",
    alreadyClaimed = "alreadyClaimed"
}
export enum Variant_ok_anonymous_alreadyRegistered {
    ok = "ok",
    anonymous = "anonymous",
    alreadyRegistered = "alreadyRegistered"
}
export enum Variant_ok_invalidStatus_notFound_notAdmin {
    ok = "ok",
    invalidStatus = "invalidStatus",
    notFound = "notFound",
    notAdmin = "notAdmin"
}
export enum Variant_ok_notFound_notAdmin {
    ok = "ok",
    notFound = "notFound",
    notAdmin = "notAdmin"
}
export enum Variant_ok_userNotFound_notAdmin {
    ok = "ok",
    userNotFound = "userNotFound",
    notAdmin = "notAdmin"
}
export enum ViewMode {
    FPP = "FPP",
    TPP = "TPP"
}
export interface backendInterface {
    adminAdjustBalance(userId: UserId, amount: bigint, txType: TransactionType): Promise<Variant_ok_userNotFound_notAdmin>;
    adminCreateTournament(args: CreateTournamentArgs): Promise<{
        __kind__: "ok";
        ok: TournamentId;
    } | {
        __kind__: "notAdmin";
        notAdmin: null;
    }>;
    adminPostRoomCode(id: TournamentId, code: string, password: string | null): Promise<Variant_ok_notFound_notAdmin>;
    adminSubmitMatchResults(tournamentId: TournamentId, results: Array<MatchResult>): Promise<Variant_ok_invalidStatus_notFound_notAdmin>;
    adminUpdateTournamentStatus(id: TournamentId, status: TournamentStatus): Promise<Variant_ok_notFound_notAdmin>;
    claimAdmin(): Promise<Variant_ok_anonymous_alreadyClaimed>;
    getMatchResults(tournamentId: TournamentId): Promise<Array<MatchResult>>;
    getMyBalance(): Promise<bigint>;
    getMyProfile(): Promise<UserView | null>;
    getMyTransactions(): Promise<Array<Transaction>>;
    getParticipants(id: TournamentId): Promise<Array<ParticipantView>>;
    getProfile(userId: UserId): Promise<UserView | null>;
    getTournament(id: TournamentId): Promise<TournamentView | null>;
    isRegistered(): Promise<boolean>;
    joinTournament(tournamentId: TournamentId, teamName: string | null): Promise<Variant_ok_alreadyJoined_tournamentFull_insufficientFunds_notJoinable_notFound_notRegistered>;
    listTournaments(): Promise<Array<TournamentView>>;
    listUsers(): Promise<Array<UserView>>;
    register(username: string): Promise<Variant_ok_anonymous_alreadyRegistered>;
}
import type { ContestType as _ContestType, CreateTournamentArgs as _CreateTournamentArgs, Game as _Game, ParticipantStatus as _ParticipantStatus, ParticipantView as _ParticipantView, TeamMode as _TeamMode, Timestamp as _Timestamp, TournamentId as _TournamentId, TournamentStatus as _TournamentStatus, TournamentView as _TournamentView, Transaction as _Transaction, TransactionId as _TransactionId, TransactionReason as _TransactionReason, TransactionType as _TransactionType, UserId as _UserId, UserView as _UserView, ViewMode as _ViewMode } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminAdjustBalance(arg0: UserId, arg1: bigint, arg2: TransactionType): Promise<Variant_ok_userNotFound_notAdmin> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAdjustBalance(arg0, arg1, to_candid_TransactionType_n1(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAdjustBalance(arg0, arg1, to_candid_TransactionType_n1(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminCreateTournament(arg0: CreateTournamentArgs): Promise<{
        __kind__: "ok";
        ok: TournamentId;
    } | {
        __kind__: "notAdmin";
        notAdmin: null;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateTournament(to_candid_CreateTournamentArgs_n4(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateTournament(to_candid_CreateTournamentArgs_n4(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminPostRoomCode(arg0: TournamentId, arg1: string, arg2: string | null): Promise<Variant_ok_notFound_notAdmin> {
        if (this.processError) {
            try {
                const result = await this.actor.adminPostRoomCode(arg0, arg1, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminPostRoomCode(arg0, arg1, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminSubmitMatchResults(arg0: TournamentId, arg1: Array<MatchResult>): Promise<Variant_ok_invalidStatus_notFound_notAdmin> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSubmitMatchResults(arg0, arg1);
                return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSubmitMatchResults(arg0, arg1);
            return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateTournamentStatus(arg0: TournamentId, arg1: TournamentStatus): Promise<Variant_ok_notFound_notAdmin> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateTournamentStatus(arg0, to_candid_TournamentStatus_n18(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateTournamentStatus(arg0, to_candid_TournamentStatus_n18(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async claimAdmin(): Promise<Variant_ok_anonymous_alreadyClaimed> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAdmin();
                return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAdmin();
            return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchResults(arg0: TournamentId): Promise<Array<MatchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchResults(arg0);
            return result;
        }
    }
    async getMyBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBalance();
            return result;
        }
    }
    async getMyProfile(): Promise<UserView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTransactions();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTransactions();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getParticipants(arg0: TournamentId): Promise<Array<ParticipantView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getParticipants(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParticipants(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: UserId): Promise<UserView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournament(arg0: TournamentId): Promise<TournamentView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournament(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournament(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async isRegistered(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isRegistered();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isRegistered();
            return result;
        }
    }
    async joinTournament(arg0: TournamentId, arg1: string | null): Promise<Variant_ok_alreadyJoined_tournamentFull_insufficientFunds_notJoinable_notFound_notRegistered> {
        if (this.processError) {
            try {
                const result = await this.actor.joinTournament(arg0, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinTournament(arg0, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTournaments(): Promise<Array<TournamentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTournaments();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTournaments();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<Array<UserView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return result;
        }
    }
    async register(arg0: string): Promise<Variant_ok_anonymous_alreadyRegistered> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0);
                return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0);
            return from_candid_variant_n51(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ContestType_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContestType): ContestType {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Game_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Game): Game {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_ParticipantStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ParticipantStatus): ParticipantStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_ParticipantView_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ParticipantView): ParticipantView {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_TeamMode_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamMode): TeamMode {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentStatus): TournamentStatus {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentView_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentView): TournamentView {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionReason_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionReason): TransactionReason {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ViewMode_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ViewMode): ViewMode {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserView]): UserView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TournamentId]): TournamentId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TournamentView]): TournamentView | null {
    return value.length === 0 ? null : from_candid_TournamentView_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TransactionId;
    userId: _UserId;
    timestamp: _Timestamp;
    txType: _TransactionType;
    amount: bigint;
    tournamentId: [] | [_TournamentId];
    reason: _TransactionReason;
}): {
    id: TransactionId;
    userId: UserId;
    timestamp: Timestamp;
    txType: TransactionType;
    amount: bigint;
    tournamentId?: TournamentId;
    reason: TransactionReason;
} {
    return {
        id: value.id,
        userId: value.userId,
        timestamp: value.timestamp,
        txType: from_candid_TransactionType_n25(_uploadFile, _downloadFile, value.txType),
        amount: value.amount,
        tournamentId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.tournamentId)),
        reason: from_candid_TransactionReason_n28(_uploadFile, _downloadFile, value.reason)
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ParticipantStatus;
    teamName: [] | [string];
    userId: _UserId;
    tournamentId: _TournamentId;
}): {
    status: ParticipantStatus;
    teamName?: string;
    userId: UserId;
    tournamentId: TournamentId;
} {
    return {
        status: from_candid_ParticipantStatus_n33(_uploadFile, _downloadFile, value.status),
        teamName: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.teamName)),
        userId: value.userId,
        tournamentId: value.tournamentId
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TournamentId;
    startTime: _Timestamp;
    status: _TournamentStatus;
    title: string;
    teamMode: _TeamMode;
    contestType: _ContestType;
    currentParticipants: bigint;
    game: _Game;
    roomPassword: [] | [string];
    viewMode: _ViewMode;
    maxParticipants: bigint;
    entryFee: bigint;
    roomCode: [] | [string];
    prizePool: bigint;
}): {
    id: TournamentId;
    startTime: Timestamp;
    status: TournamentStatus;
    title: string;
    teamMode: TeamMode;
    contestType: ContestType;
    currentParticipants: bigint;
    game: Game;
    roomPassword?: string;
    viewMode: ViewMode;
    maxParticipants: bigint;
    entryFee: bigint;
    roomCode?: string;
    prizePool: bigint;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_TournamentStatus_n39(_uploadFile, _downloadFile, value.status),
        title: value.title,
        teamMode: from_candid_TeamMode_n41(_uploadFile, _downloadFile, value.teamMode),
        contestType: from_candid_ContestType_n43(_uploadFile, _downloadFile, value.contestType),
        currentParticipants: value.currentParticipants,
        game: from_candid_Game_n45(_uploadFile, _downloadFile, value.game),
        roomPassword: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.roomPassword)),
        viewMode: from_candid_ViewMode_n47(_uploadFile, _downloadFile, value.viewMode),
        maxParticipants: value.maxParticipants,
        entryFee: value.entryFee,
        roomCode: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.roomCode)),
        prizePool: value.prizePool
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TournamentId;
} | {
    notAdmin: null;
}): {
    __kind__: "ok";
    ok: TournamentId;
} | {
    __kind__: "notAdmin";
    notAdmin: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "notAdmin" in value ? {
        __kind__: "notAdmin",
        notAdmin: value.notAdmin
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    notFound: null;
} | {
    notAdmin: null;
}): Variant_ok_notFound_notAdmin {
    return "ok" in value ? Variant_ok_notFound_notAdmin.ok : "notFound" in value ? Variant_ok_notFound_notAdmin.notFound : "notAdmin" in value ? Variant_ok_notFound_notAdmin.notAdmin : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    invalidStatus: null;
} | {
    notFound: null;
} | {
    notAdmin: null;
}): Variant_ok_invalidStatus_notFound_notAdmin {
    return "ok" in value ? Variant_ok_invalidStatus_notFound_notAdmin.ok : "invalidStatus" in value ? Variant_ok_invalidStatus_notFound_notAdmin.invalidStatus : "notFound" in value ? Variant_ok_invalidStatus_notFound_notAdmin.notFound : "notAdmin" in value ? Variant_ok_invalidStatus_notFound_notAdmin.notAdmin : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    anonymous: null;
} | {
    alreadyClaimed: null;
}): Variant_ok_anonymous_alreadyClaimed {
    return "ok" in value ? Variant_ok_anonymous_alreadyClaimed.ok : "anonymous" in value ? Variant_ok_anonymous_alreadyClaimed.anonymous : "alreadyClaimed" in value ? Variant_ok_anonymous_alreadyClaimed.alreadyClaimed : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Debit: null;
} | {
    Credit: null;
}): TransactionType {
    return "Debit" in value ? TransactionType.Debit : "Credit" in value ? TransactionType.Credit : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Refund: null;
} | {
    EntryFee: null;
} | {
    PrizeWin: null;
} | {
    Signup: null;
}): TransactionReason {
    return "Refund" in value ? TransactionReason.Refund : "EntryFee" in value ? TransactionReason.EntryFee : "PrizeWin" in value ? TransactionReason.PrizeWin : "Signup" in value ? TransactionReason.Signup : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    userNotFound: null;
} | {
    notAdmin: null;
}): Variant_ok_userNotFound_notAdmin {
    return "ok" in value ? Variant_ok_userNotFound_notAdmin.ok : "userNotFound" in value ? Variant_ok_userNotFound_notAdmin.userNotFound : "notAdmin" in value ? Variant_ok_userNotFound_notAdmin.notAdmin : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Eliminated: null;
} | {
    Joined: null;
} | {
    Completed: null;
}): ParticipantStatus {
    return "Eliminated" in value ? ParticipantStatus.Eliminated : "Joined" in value ? ParticipantStatus.Joined : "Completed" in value ? ParticipantStatus.Completed : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Live: null;
} | {
    WaitingResults: null;
} | {
    RoomCodePosted: null;
} | {
    Cancelled: null;
} | {
    Completed: null;
} | {
    Upcoming: null;
}): TournamentStatus {
    return "Live" in value ? TournamentStatus.Live : "WaitingResults" in value ? TournamentStatus.WaitingResults : "RoomCodePosted" in value ? TournamentStatus.RoomCodePosted : "Cancelled" in value ? TournamentStatus.Cancelled : "Completed" in value ? TournamentStatus.Completed : "Upcoming" in value ? TournamentStatus.Upcoming : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Duo: null;
} | {
    Squad: null;
} | {
    Solo: null;
}): TeamMode {
    return "Duo" in value ? TeamMode.Duo : "Squad" in value ? TeamMode.Squad : "Solo" in value ? TeamMode.Solo : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Damage: null;
} | {
    TopPosition: null;
} | {
    MostKills: null;
}): ContestType {
    return "Damage" in value ? ContestType.Damage : "TopPosition" in value ? ContestType.TopPosition : "MostKills" in value ? ContestType.MostKills : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    BGMI: null;
} | {
    FreeFire: null;
}): Game {
    return "BGMI" in value ? Game.BGMI : "FreeFire" in value ? Game.FreeFire : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FPP: null;
} | {
    TPP: null;
}): ViewMode {
    return "FPP" in value ? ViewMode.FPP : "TPP" in value ? ViewMode.TPP : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    alreadyJoined: null;
} | {
    tournamentFull: null;
} | {
    insufficientFunds: null;
} | {
    notJoinable: null;
} | {
    notFound: null;
} | {
    notRegistered: null;
}): Variant_ok_alreadyJoined_tournamentFull_insufficientFunds_notJoinable_notFound_notRegistered {
    return "ok" in value ? Variant_ok_alreadyJoined_tournamentFull_insufficientFunds_notJoinable_notFound_notRegistered.ok : "alreadyJoined" in value ? Variant_ok_alreadyJoined_tournamentFull_insufficientFunds_notJoinable_notFound_notRegistered.alreadyJoined : "tournamentFull" in value ? Variant_ok_alreadyJoined_tournamentFull_insufficientFunds_notJoinable_notFound_notRegistered.tournamentFull : "insufficientFunds" in value ? Variant_ok_alreadyJoined_tournamentFull_insufficientFunds_notJoinable_notFound_notRegistered.insufficientFunds : "notJoinable" in value ? Variant_ok_alreadyJoined_tournamentFull_insufficientFunds_notJoinable_notFound_notRegistered.notJoinable : "notFound" in value ? Variant_ok_alreadyJoined_tournamentFull_insufficientFunds_notJoinable_notFound_notRegistered.notFound : "notRegistered" in value ? Variant_ok_alreadyJoined_tournamentFull_insufficientFunds_notJoinable_notFound_notRegistered.notRegistered : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    anonymous: null;
} | {
    alreadyRegistered: null;
}): Variant_ok_anonymous_alreadyRegistered {
    return "ok" in value ? Variant_ok_anonymous_alreadyRegistered.ok : "anonymous" in value ? Variant_ok_anonymous_alreadyRegistered.anonymous : "alreadyRegistered" in value ? Variant_ok_anonymous_alreadyRegistered.alreadyRegistered : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ParticipantView>): Array<ParticipantView> {
    return value.map((x)=>from_candid_ParticipantView_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TournamentView>): Array<TournamentView> {
    return value.map((x)=>from_candid_TournamentView_n37(_uploadFile, _downloadFile, x));
}
function to_candid_ContestType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContestType): _ContestType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_CreateTournamentArgs_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateTournamentArgs): _CreateTournamentArgs {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_Game_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Game): _Game {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_TeamMode_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeamMode): _TeamMode {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_TournamentStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentStatus): _TournamentStatus {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ViewMode_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ViewMode): _ViewMode {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: Timestamp;
    title: string;
    teamMode: TeamMode;
    contestType: ContestType;
    game: Game;
    viewMode: ViewMode;
    maxParticipants: bigint;
    entryFee: bigint;
    prizePool: bigint;
}): {
    startTime: _Timestamp;
    title: string;
    teamMode: _TeamMode;
    contestType: _ContestType;
    game: _Game;
    viewMode: _ViewMode;
    maxParticipants: bigint;
    entryFee: bigint;
    prizePool: bigint;
} {
    return {
        startTime: value.startTime,
        title: value.title,
        teamMode: to_candid_TeamMode_n6(_uploadFile, _downloadFile, value.teamMode),
        contestType: to_candid_ContestType_n8(_uploadFile, _downloadFile, value.contestType),
        game: to_candid_Game_n10(_uploadFile, _downloadFile, value.game),
        viewMode: to_candid_ViewMode_n12(_uploadFile, _downloadFile, value.viewMode),
        maxParticipants: value.maxParticipants,
        entryFee: value.entryFee,
        prizePool: value.prizePool
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Game): {
    BGMI: null;
} | {
    FreeFire: null;
} {
    return value == Game.BGMI ? {
        BGMI: null
    } : value == Game.FreeFire ? {
        FreeFire: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ViewMode): {
    FPP: null;
} | {
    TPP: null;
} {
    return value == ViewMode.FPP ? {
        FPP: null
    } : value == ViewMode.TPP ? {
        TPP: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentStatus): {
    Live: null;
} | {
    WaitingResults: null;
} | {
    RoomCodePosted: null;
} | {
    Cancelled: null;
} | {
    Completed: null;
} | {
    Upcoming: null;
} {
    return value == TournamentStatus.Live ? {
        Live: null
    } : value == TournamentStatus.WaitingResults ? {
        WaitingResults: null
    } : value == TournamentStatus.RoomCodePosted ? {
        RoomCodePosted: null
    } : value == TournamentStatus.Cancelled ? {
        Cancelled: null
    } : value == TournamentStatus.Completed ? {
        Completed: null
    } : value == TournamentStatus.Upcoming ? {
        Upcoming: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    Debit: null;
} | {
    Credit: null;
} {
    return value == TransactionType.Debit ? {
        Debit: null
    } : value == TransactionType.Credit ? {
        Credit: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeamMode): {
    Duo: null;
} | {
    Squad: null;
} | {
    Solo: null;
} {
    return value == TeamMode.Duo ? {
        Duo: null
    } : value == TeamMode.Squad ? {
        Squad: null
    } : value == TeamMode.Solo ? {
        Solo: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContestType): {
    Damage: null;
} | {
    TopPosition: null;
} | {
    MostKills: null;
} {
    return value == ContestType.Damage ? {
        Damage: null
    } : value == ContestType.TopPosition ? {
        TopPosition: null
    } : value == ContestType.MostKills ? {
        MostKills: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
